-- Snowflake setup for ELT Airflow Snowflake project

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE AIRFLOW_DB;

USE DATABASE AIRFLOW_DB;

CREATE OR REPLACE SCHEMA BRONZE;
CREATE OR REPLACE SCHEMA SILVER;
CREATE OR REPLACE SCHEMA GOLD;

USE SCHEMA AIRFLOW_DB.BRONZE;

CREATE OR REPLACE STORAGE INTEGRATION AIRFLOW_S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::272987324508:role/snowflake-load-role-elt-airflow'
  STORAGE_ALLOWED_LOCATIONS = ('s3://jennyarias-elt-airflow-data/');

DESC INTEGRATION AIRFLOW_S3_INT;
