-- Create external stage after AWS trust policy update

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE AIRFLOW_DB;
USE SCHEMA BRONZE;

CREATE OR REPLACE STAGE AIRFLOW_DB.BRONZE.AIRFLOW_S3_STAGE
  STORAGE_INTEGRATION = AIRFLOW_S3_INT
  URL = 's3://jennyarias-elt-airflow-data/';

LIST @AIRFLOW_DB.BRONZE.AIRFLOW_S3_STAGE;
