-- Validate ELT pipeline outputs across Bronze, Silver, and Gold

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE AIRFLOW_DB;

-- Row counts across all pipeline tables
SELECT 'BRONZE.DOCTORS_RAW' AS table_name, COUNT(*) AS row_count FROM AIRFLOW_DB.BRONZE.DOCTORS_RAW
UNION ALL
SELECT 'BRONZE.HOSPITALS_RAW', COUNT(*) FROM AIRFLOW_DB.BRONZE.HOSPITALS_RAW
UNION ALL
SELECT 'BRONZE.PATIENTS_RAW', COUNT(*) FROM AIRFLOW_DB.BRONZE.PATIENTS_RAW
UNION ALL
SELECT 'BRONZE.TREATMENTS_RAW', COUNT(*) FROM AIRFLOW_DB.BRONZE.TREATMENTS_RAW
UNION ALL
SELECT 'BRONZE.VISITS_RAW', COUNT(*) FROM AIRFLOW_DB.BRONZE.VISITS_RAW
UNION ALL
SELECT 'SILVER.PATIENTS_TRANSFORM', COUNT(*) FROM AIRFLOW_DB.SILVER.PATIENTS_TRANSFORM
UNION ALL
SELECT 'SILVER.TREATMENTS_TRANSFORM', COUNT(*) FROM AIRFLOW_DB.SILVER.TREATMENTS_TRANSFORM
UNION ALL
SELECT 'SILVER.VISITS_TRANSFORM', COUNT(*) FROM AIRFLOW_DB.SILVER.VISITS_TRANSFORM
UNION ALL
SELECT 'GOLD.CITY_HEALTHCARE_ACCESS_AGG', COUNT(*) FROM AIRFLOW_DB.GOLD.CITY_HEALTHCARE_ACCESS_AGG
UNION ALL
SELECT 'GOLD.HOSPITAL_PERFORMANCE_AGG', COUNT(*) FROM AIRFLOW_DB.GOLD.HOSPITAL_PERFORMANCE_AGG
UNION ALL
SELECT 'GOLD.PATIENT_VALUE_AGG', COUNT(*) FROM AIRFLOW_DB.GOLD.PATIENT_VALUE_AGG
UNION ALL
SELECT 'GOLD.PATIENT_VISIT_SUMMARY_AGG', COUNT(*) FROM AIRFLOW_DB.GOLD.PATIENT_VISIT_SUMMARY_AGG
ORDER BY table_name;

-- Representative samples
SELECT * FROM AIRFLOW_DB.BRONZE.PATIENTS_RAW LIMIT 5;
SELECT * FROM AIRFLOW_DB.SILVER.PATIENTS_TRANSFORM LIMIT 5;
SELECT * FROM AIRFLOW_DB.GOLD.HOSPITAL_PERFORMANCE_AGG LIMIT 5;
